Theoretical Questions:-

In [1]:
# Ques 1:- Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
# Ans:- NumPy is essential in scientific computing and data analysis because it provides efficient handling of large multi-dimensional arrays and matrices, along with a wide array of mathematical functions. Its advantages include:
# *Fast performance due to optimized C-based operations.
# *Memory efficiency with compact data structures.
# *Broad functionality for linear algebra, random numbers, and more.
# *Seamless integration with other scientific libraries like SciPy, Pandas, and Matplotlib. Overall, NumPy enhances Python by enabling faster and more efficient numerical operations, critical for handling large datasets and complex computations.

In [2]:
# Ques 2:- Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
# Ans:-  Both np.mean() and np.average() in NumPy compute the arithmetic mean, but they differ in key ways:
# *np.mean():
# Calculates the simple average of the array elements.
# Does not consider weights.
# Used when you need the standard mean without any weighting.
# *np.average():
# Allows for weighted averages by accepting a weights parameter.
# If no weights are provided, it behaves like np.mean().
# *Use Case:
# Use np.mean() when you need a straightforward average.
# Use np.average() when you want to compute a weighted mean.

In [4]:
# Ques 3:- Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
# Ans:- You can reverse a NumPy array along different axes using slicing or the np.flip() function:
# 1. For 1D array:
# Using slicing: arr[::-1]
# Using np.flip(): np.flip(arr)
import numpy as np
arr_1d = np.array([1, 2, 3, 4])
reversed_1d = arr_1d[::-1]  # [4, 3, 2, 1]
# 2. . For 2D array:
# Reverse rows (along axis 0): arr[::-1, :] or np.flip(arr, axis=0)
# Reverse columns (along axis 1): arr[:, ::-1] or np.flip(arr, axis=1)
# Reverse both axes: np.flip(arr)
arr_2d = np.array([[1, 2], [3, 4]])
reversed_rows = arr_2d[::-1, :]  # [[3, 4], [1, 2]]
reversed_cols = arr_2d[:, ::-1]  # [[2, 1], [4, 3]]

In [5]:
# Ques 4:-  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
# Ans:- To determine the data type of elements in a NumPy array, use the dtype attribute:
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64 (for example)
# Importance of Data Types:
# Memory Management: Data types define how much memory each element requires (e.g., int32 uses less memory than int64).
# Performance: Choosing the right data type optimizes memory usage and improves computational efficiency, especially when dealing with large arrays or performing intensive calculations.

int64


In [6]:
# Ques 5:-  Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
# Ans:- ndarray (N-dimensional array) is the core data structure in NumPy, designed for efficient numerical computations.
# *Key Features:
# Homogeneous elements: All elements have the same data type.
# Fixed size: Once created, the size of an ndarray is fixed.
# Efficient memory use: Stored in contiguous memory blocks, enabling faster access and operations.
# Supports multi-dimensional data: Can handle arrays with any number of dimensions (1D, 2D, 3D, etc.).
# Broadcasting: Supports element-wise operations without the need for explicit loops.
# *Differences from Python Lists:
# Performance: ndarray is much faster and more memory-efficient than lists.
# Homogeneity: All elements in an ndarray must be of the same type, whereas lists can hold mixed types.
# Advanced operations: NumPy arrays support vectorized operations and broadcasting, which lists do not.

In [7]:
# Ques 6:-  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
# Ans:- NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to:
# *Memory Efficiency: NumPy arrays store elements in contiguous memory blocks, reducing overhead compared to lists, which store pointers to objects.
# *Vectorization: NumPy allows for element-wise operations without explicit loops, leveraging optimized C and Fortran code, making operations much faster.
# *Fixed Data Types: Arrays have a single data type, leading to more efficient memory use and quicker operations compared to heterogeneous Python lists.
# *Built-in Functions: NumPy provides optimized mathematical functions, further enhancing performance for large datasets.
# These advantages make NumPy ideal for high-performance computing tasks.

In [8]:
# Ques 7:- Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
# Ans:-
# In NumPy, vstack() and hstack() are used to stack arrays vertically and horizontally, respectively:
# *vstack() (Vertical Stack):
# Stacks arrays along the vertical axis (row-wise).
# Example:-
a = np.array([1, 2])
b = np.array([3, 4])
np.vstack((a, b))
# Output:
# [[1, 2],
#  [3, 4]]
# *hstack() (Horizontal Stack):
# Stacks arrays along the horizontal axis (column-wise).
# Example:-
a = np.array([1, 2])
b = np.array([3, 4])
np.hstack((a, b))
# Output: [1, 2, 3, 4]
# vstack() is used for vertical stacking (adding rows), while hstack() is used for horizontal stacking (adding columns).

array([1, 2, 3, 4])

In [ ]:
# Ques 8:-  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
# Ans:- In NumPy, fliplr() and flipud() are used to flip arrays along specific axes:
# fliplr() (Flip Left to Right):
# Flips the array horizontally (reverses the order of columns).
# Applicable to 2D arrays or higher.
# Example:- arr = np.array([[1, 2], [3, 4]])
np.fliplr(arr)
# Output: [[2, 1], [4, 3]]
# flipud() (Flip Up to Down):
# Flips the array vertically (reverses the order of rows).
# Example:
np.flipud(arr)
# Output: [[3, 4], [1, 2]]
# fliplr() flips along the horizontal axis (columns), while flipud() flips along the vertical axis (rows). Both are useful for manipulating 2D or multi-dimensional arrays.

In [ ]:
# Ques 9:-  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
# Ans:-
# The array_split() method in NumPy splits an array into specified sub-arrays. Unlike split(), it handles uneven splits by distributing elements as evenly as possible among the sub-arrays.
# Handling Uneven Splits:
# If the array cannot be split evenly, the extra elements are added to the earlier sub-arrays.
# Example:-
arr = np.array([1, 2, 3, 4, 5])
np.array_split(arr, 3)
# Output: [array([1, 2]), array([3, 4]), array([5])]
# Here, the array is split into three parts, with one extra element in the first two sub-arrays.
# This ensures flexibility when the array size isn't perfectly divisible.

In [ ]:
# Ques 10:- Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
# Ans:-
# *Vectorization:
# Definition: Vectorization refers to the process of performing operations on entire arrays or large datasets at once, rather than using explicit loops.
# Benefit: It leverages optimized low-level implementations (often in C or Fortran) for faster execution, reducing overhead and improving performance significantly.
# *Broadcasting:
# Definition: Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes.
# How it Works: NumPy automatically expands the smaller array’s dimensions to match the larger array’s shape, enabling element-wise operations without requiring explicit replication of data.
# *Contribution to Efficient Array Operations:
# Reduced Complexity: Vectorization and broadcasting simplify code by eliminating the need for loops, making it more readable and maintainable.
# Performance Gains: Both techniques take advantage of low-level optimizations, resulting in faster computations, especially for large datasets.
# Together, vectorization and broadcasting make NumPy powerful for numerical computations, allowing for efficient and concise operations on arrays.

Practical Questions


In [10]:
# Ques 1:- Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
# Ans:-
import numpy as np
# Create a 3x3 NumPy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))
# Interchange rows and columns (transpose the array)
transposed_array = array_3x3.T
# Print the original and transposed arrays
print("Original Array:")
print(array_3x3)
print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[67 43 71]
 [26 85  1]
 [37  5 15]]

Transposed Array:
[[67 26 37]
 [43 85  5]
 [71  1 15]]


In [11]:
# Ques 2:-  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
# Ans:-
import numpy as np
# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # This creates an array with elements from 0 to 9
# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
# Print the original and reshaped arrays
print("Original 1D Array:")
print(array_1d)
print("\nReshaped to 2x5 Array:")
print(array_2x5)
print("\nReshaped to 5x2 Array:")
print(array_5x2)

Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
# Ques 3:-  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
# Ans:-
import numpy as np
# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)
# Add a border of zeros around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
# Print the original and the new array
print("Original 4x4 Array:")
print(array_4x4)
print("\n6x6 Array with a border of zeros:")
print(array_with_border)

Original 4x4 Array:
[[0.8465066  0.94881015 0.06011878 0.64784169]
 [0.13300236 0.99304654 0.25733877 0.82518382]
 [0.4308654  0.59362646 0.14127102 0.69296103]
 [0.0766175  0.21116008 0.87808206 0.55843178]]

6x6 Array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.8465066  0.94881015 0.06011878 0.64784169 0.        ]
 [0.         0.13300236 0.99304654 0.25733877 0.82518382 0.        ]
 [0.         0.4308654  0.59362646 0.14127102 0.69296103 0.        ]
 [0.         0.0766175  0.21116008 0.87808206 0.55843178 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [13]:
# Ques 4:- Using NumPy, create an array of integers from 10 to 60 with a step of 5.
# Ans:-
import numpy as np
# Create an array of integers from 10 to 60 with a step of 5
array_step = np.arange(10, 61, 5)
# Print the resulting array
print("Array of integers from 10 to 60 with a step of 5:")
print(array_step)

Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [14]:
# Ques 5:-  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
# Ans:-
import numpy as np
# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])
# Apply different case transformations
uppercase_array = np.char.upper(array_strings)
lowercase_array = np.char.lower(array_strings)
titlecase_array = np.char.title(array_strings)
# Print the original and transformed arrays
print("Original Array:")
print(array_strings)
print("\nUppercase Transformation:")
print(uppercase_array)
print("\nLowercase Transformation:")
print(lowercase_array)
print("\nTitle Case Transformation:")
print(titlecase_array)

Original Array:
['python' 'numpy' 'pandas']

Uppercase Transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
['python' 'numpy' 'pandas']

Title Case Transformation:
['Python' 'Numpy' 'Pandas']


In [19]:
# Ques 6:- Generate a NumPy array of words. Insert a space between each character of every word in the array.
# Ans:-
import numpy as np
# Create a NumPy array of words
array_words = np.array(['hello', 'world', 'numpy', 'array'])
# Insert a space between each character of every word
spaced_words = np.char.join(' ', array_words)
# Print the original and transformed arrays
print("Original Array of Words:")
print(array_words)
print("\nArray with Spaces Between Characters:")
print(spaced_words)

Original Array of Words:
['hello' 'world' 'numpy' 'array']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


In [20]:
# Ques 7:-  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
# Ans:-
import numpy as np
# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
array2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])
# Perform element-wise addition
addition = array1 + array2
# Perform element-wise subtraction
subtraction = array1 - array2
# Perform element-wise multiplication
multiplication = array1 * array2
# Perform element-wise division
division = array1 / array2
# Print the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise Division:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [21]:
# Ques 8:- . Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
# Ans:-
import numpy as np
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
# Print the identity matrix and its diagonal elements
print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [22]:
# Ques 9:-Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
# Ans:-
import numpy as np
# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True
# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)
# Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]
# Print the random array and the prime numbers found
print("Random Array:")
print(random_array)
print("\nPrime Numbers in the Array:")
print(prime_numbers)

Random Array:
[402 466 324 523 254 417 620 381 833 997 982 743 301 244 130 720 423 567
 962 854 484 903 631 457 710 400 129 590 678   2 388 958 935 710 667 158
 865 552 187 870 111 744 147 100  40 179 571 820 151 283 467 253 396  11
 756 651 110 345 432 885 241 779 103 746  10 356 885 584 551 308 122 436
 331 460 995 486 258 787 454 640 437 463 960 622 358 887 759 574 986 382
 671 268 729 259 560 290 446  64 986 563]

Prime Numbers in the Array:
[523, 997, 743, 631, 457, 2, 179, 571, 151, 283, 467, 11, 241, 103, 331, 787, 463, 887, 563]


In [23]:
# Ques 10:-. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages
# Ans:-
import numpy as np
# Create a NumPy array representing daily temperatures for a month (30 days)
# Using random temperatures between 20 and 35 degrees Celsius
daily_temperatures = np.random.randint(20, 36, size=30)
# Calculate the number of complete weeks (4 complete weeks)
num_weeks = len(daily_temperatures) // 7
# Reshape the array into a 4-week format (7 days each)
weekly_temperatures = daily_temperatures[:num_weeks * 7].reshape(num_weeks, 7)
# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)
# Print the daily temperatures and the weekly averages
print("Daily Temperatures for the Month:")
print(daily_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures for the Month:
[29 26 25 33 24 30 21 24 22 35 26 27 26 26 31 29 21 21 30 25 26 25 35 22
 30 24 29 26 34 27]

Weekly Averages:
[26.85714286 26.57142857 26.14285714 27.28571429]
